# Generated by Django 3.2.19 on 2023-07-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=True, verbose_name='accepted terms'),
        ),
    ]
